apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-secret-demo
  template:
    metadata:
      labels:
        app: cm-secret-demo
    spec:
      containers:
        - name: demo
          image: busybox:1.36
          command: ["sh","-c"]
          args:
            - |
              echo "=== ENV 확인 ===";
              echo "DB_USER=$DB_USER";
              echo "DB_PASS=$DB_PASS";
              echo "LOG_LEVEL=$LOG_LEVEL";
              echo "=== 파일 확인 ===";
              echo "[/etc/config/application.properties]";
              cat /etc/config/application.properties || true;
              echo "[/etc/secret/credentials.json]";
              cat /etc/secret/credentials.json || true;
              echo "=== 대기 ===";
              sleep 3600
          # 1) 개별 키로 ENV 주입
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASS
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL
          # 2) 파일로 마운트 (ConfigMap/Secret 모두)
          volumeMounts:
            - name: cfg
              mountPath: /etc/config
              readOnly: true
            - name: sec
              mountPath: /etc/secret
              readOnly: true
      volumes:
        - name: cfg
          configMap:
            name: app-config
            # 특정 키만 파일로 택해도 됨 (전체를 마운트하면 생략 가능)
            items:
              - key: application.properties
                path: application.properties
        - name: sec
          secret:
            name: app-secret
            # 권한 조정이 필요하면 defaultMode 사용 (8진수)
            # defaultMode: 0400
            items:
              - key: credentials.json
                path: credentials.json
