apiVersion: apps/v1
kind: Deployment
metadata:
  name: etc-guestbook-ui-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - name: c-etc-guestbook-ui
          image: bitnami/nginx:latest
          env:
            # 명시적으로 8080으로 띄우기(이미 기본이지만 헷갈림 방지)
            - name: NGINX_HTTP_PORT_NUMBER
              value: "8080"
          ports:
            - name: http
              containerPort: 8080