apiVersion: apps/v1
kind: Deployment
metadata:
  name: etc-guestbook-ui-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: bitnami/nginx
        name: c-etc-guestbook-ui
        ports:
        - containerPort: 80
